/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpokenEnglishRouteImport } from './routes/spoken-english'
import { Route as PteRouteImport } from './routes/pte'
import { Route as IeltsRouteImport } from './routes/ielts'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CelpipRouteImport } from './routes/celpip'
import { Route as BusinessCommunicationsRouteImport } from './routes/business-communications'
import { Route as BookSessionRouteImport } from './routes/book-session'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersTeacherIdRouteImport } from './routes/teachers.$teacherId'

const SpokenEnglishRoute = SpokenEnglishRouteImport.update({
  id: '/spoken-english',
  path: '/spoken-english',
  getParentRoute: () => rootRouteImport,
} as any)
const PteRoute = PteRouteImport.update({
  id: '/pte',
  path: '/pte',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsRoute = IeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CelpipRoute = CelpipRouteImport.update({
  id: '/celpip',
  path: '/celpip',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCommunicationsRoute = BusinessCommunicationsRouteImport.update({
  id: '/business-communications',
  path: '/business-communications',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book-session',
  path: '/book-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersTeacherIdRoute = TeachersTeacherIdRouteImport.update({
  id: '/teachers/$teacherId',
  path: '/teachers/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-session': typeof BookSessionRoute
  '/business-communications': typeof BusinessCommunicationsRoute
  '/celpip': typeof CelpipRoute
  '/contact-us': typeof ContactUsRoute
  '/enroll': typeof EnrollRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-session': typeof BookSessionRoute
  '/business-communications': typeof BusinessCommunicationsRoute
  '/celpip': typeof CelpipRoute
  '/contact-us': typeof ContactUsRoute
  '/enroll': typeof EnrollRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book-session': typeof BookSessionRoute
  '/business-communications': typeof BusinessCommunicationsRoute
  '/celpip': typeof CelpipRoute
  '/contact-us': typeof ContactUsRoute
  '/enroll': typeof EnrollRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
  '/teachers/$teacherId': typeof TeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book-session'
    | '/business-communications'
    | '/celpip'
    | '/contact-us'
    | '/enroll'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
    | '/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book-session'
    | '/business-communications'
    | '/celpip'
    | '/contact-us'
    | '/enroll'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
    | '/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book-session'
    | '/business-communications'
    | '/celpip'
    | '/contact-us'
    | '/enroll'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
    | '/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookSessionRoute: typeof BookSessionRoute
  BusinessCommunicationsRoute: typeof BusinessCommunicationsRoute
  CelpipRoute: typeof CelpipRoute
  ContactUsRoute: typeof ContactUsRoute
  EnrollRoute: typeof EnrollRoute
  IeltsRoute: typeof IeltsRoute
  PteRoute: typeof PteRoute
  SpokenEnglishRoute: typeof SpokenEnglishRoute
  TeachersTeacherIdRoute: typeof TeachersTeacherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spoken-english': {
      id: '/spoken-english'
      path: '/spoken-english'
      fullPath: '/spoken-english'
      preLoaderRoute: typeof SpokenEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pte': {
      id: '/pte'
      path: '/pte'
      fullPath: '/pte'
      preLoaderRoute: typeof PteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts': {
      id: '/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof IeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celpip': {
      id: '/celpip'
      path: '/celpip'
      fullPath: '/celpip'
      preLoaderRoute: typeof CelpipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-communications': {
      id: '/business-communications'
      path: '/business-communications'
      fullPath: '/business-communications'
      preLoaderRoute: typeof BusinessCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-session': {
      id: '/book-session'
      path: '/book-session'
      fullPath: '/book-session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$teacherId': {
      id: '/teachers/$teacherId'
      path: '/teachers/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof TeachersTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookSessionRoute: BookSessionRoute,
  BusinessCommunicationsRoute: BusinessCommunicationsRoute,
  CelpipRoute: CelpipRoute,
  ContactUsRoute: ContactUsRoute,
  EnrollRoute: EnrollRoute,
  IeltsRoute: IeltsRoute,
  PteRoute: PteRoute,
  SpokenEnglishRoute: SpokenEnglishRoute,
  TeachersTeacherIdRoute: TeachersTeacherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
