/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpokenEnglishRouteImport } from './routes/spoken-english'
import { Route as PteRouteImport } from './routes/pte'
import { Route as IeltsRouteImport } from './routes/ielts'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as BookSessionRouteImport } from './routes/book-session'
import { Route as IndexRouteImport } from './routes/index'

const SpokenEnglishRoute = SpokenEnglishRouteImport.update({
  id: '/spoken-english',
  path: '/spoken-english',
  getParentRoute: () => rootRouteImport,
} as any)
const PteRoute = PteRouteImport.update({
  id: '/pte',
  path: '/pte',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsRoute = IeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book-session',
  path: '/book-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRoute
  '/contact-us': typeof ContactUsRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRoute
  '/contact-us': typeof ContactUsRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-session': typeof BookSessionRoute
  '/contact-us': typeof ContactUsRoute
  '/ielts': typeof IeltsRoute
  '/pte': typeof PteRoute
  '/spoken-english': typeof SpokenEnglishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-session'
    | '/contact-us'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-session'
    | '/contact-us'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
  id:
    | '__root__'
    | '/'
    | '/book-session'
    | '/contact-us'
    | '/ielts'
    | '/pte'
    | '/spoken-english'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookSessionRoute: typeof BookSessionRoute
  ContactUsRoute: typeof ContactUsRoute
  IeltsRoute: typeof IeltsRoute
  PteRoute: typeof PteRoute
  SpokenEnglishRoute: typeof SpokenEnglishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spoken-english': {
      id: '/spoken-english'
      path: '/spoken-english'
      fullPath: '/spoken-english'
      preLoaderRoute: typeof SpokenEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pte': {
      id: '/pte'
      path: '/pte'
      fullPath: '/pte'
      preLoaderRoute: typeof PteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts': {
      id: '/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof IeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-session': {
      id: '/book-session'
      path: '/book-session'
      fullPath: '/book-session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookSessionRoute: BookSessionRoute,
  ContactUsRoute: ContactUsRoute,
  IeltsRoute: IeltsRoute,
  PteRoute: PteRoute,
  SpokenEnglishRoute: SpokenEnglishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
